<?php

namespace W7\App\Provider;

use W7\Core\Provider\ProviderAbstract;

class TestProvider extends ProviderAbstract {
	public function register() {
		parent::register(); // TODO: Change the autogenerated stub
	}
}